package com.epam.pharmacy.util.constant;

public final class ProjectConstant {
    public static final String EN_LOCALE_LANG = "en";
    public static final String EN_LOCALE_COUNTRY = "US";
    public static final String BY_LOCALE_LANG = "be";
    public static final String BY_LOCALE_COUNTRY = "BY";
    public static final String RU_LOCALE_LANG = "ru";
    public static final String RU_LOCALE_COUNTRY = "RU";
    public static final String COMMAND = "command";
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String CLIENT = "client";
    public static final String DOCTOR = "doctor";
    public static final String PHARMACIST = "pharmacist";
    public static final String ROLE = "role";
    public static final String ID = "id";
    public static final String USER = "user";
    public static final String PASS1 = "pass1";
    public static final String PASS2 = "pass2";
    public static final String LOCALE = "locale";
    public static final String REDIRECT_PATH = "redirectPath";
    public static final String DRUGS = "drugs";
    public static final String DRUG = "drug";
    public static final String PAGE = "page";
    public static final String INDEX = "index";
    public static final String SECURITY_REDIRECT = "securityRedirect";
    public static final String CART = "cart";
    public static final String NUMBER = "number";
    public static final String ORDER = "order";
    public static final String DRUG_SEARCH = "drugsearch";
    public static final String PAYMENT = "payment";
    public static final String ID_CLIENT = "id_client";
    public static final String ID_DRUG = "id_drug";
    public static final String PATIENT_ID = "patient_id";
    public static final String DOCTOR_ID = "doctor_id";
    public static final String DRUG_ID = "drug_id";
    public static final String TYPE = "type";
    public static final String FROM = "from";
    public static final String TO = "to";
    public static final String SERIALNUMBER = "serialnumber";
    public static final String USED = "used";
    public static final String RECIPE = "recipe";
    public static final String RECIPES = "recipes";
    public static final String NO_SUCH_DRUG = "no_such_drug";
    public static final String REQUEST_DRUG_ID = "requestDrugId";
    public static final String REQUEST_RECIPE_TYPE = "requestRecipeType";
    public static final String RECIPE_REQUEST = "recipeRequest";
    public static final String CLINT_ID = "clientId";
    public static final String DOCTORS = "doctors";
    public static final String DOCTOR_QUERIES = "doctorsQueries";
    public static final String PHARMACIST_QUERIES = "pharmacistQueries";
    public static final String DATE_OF_BIRTH = "dateOfBirth";
    public static final String NAME = "name";
    public static final String INN = "inn";
    public static final String COMPOSITE = "composite";
    public static final String FORM = "form";
    public static final String PATRONYMIC = "patronymic";
    public static final String DOSE = "dose";
    public static final String SHELFLIFE = "shelfLife";
    public static final String PRICE = "price";
    public static final String RECIPE_TYPE = "recipeType";
    public static final String AVAILABILITY = "availability";
    public static final String AMOUNT = "amount";
    public static final String ORDER_TIME = "orderTime";
    public static final String ANNOTATION = "annotation";
    public static final String ARCHIVE = "archive";
    public static final String DATE_FORMAT = "dd-MM-yyyy";

    private ProjectConstant(){
        throw new IllegalStateException("Utility class");
    }
}
